# Kaggle Competition info:
## NVIDIA Nemotron Model Reasoning Challenge
#### Advance reasoning techniques using NVIDIA Nemotron open models on a novel benchmark

## Overview
Develop techniques that improve reasoning accuracy using NVIDIA Nemotron models.

Participants will experiment with prompting, data pipelines, and lightweight fine-tuning while evaluating their approaches on a new reasoning benchmark developed by NVIDIA Research.

**Link:** <https://www.kaggle.com/competitions/nvidia-nemotron-model-reasoning-challenge/overview>


### Use my Generate COT Data for Fine Tuning:
**Link:** <https://www.kaggle.com/datasets/johnsonhk88/nemotron-model-reasoning-challenge-generate-cot>

## Install libary

In [1]:
install_DIR= "kaggle/input/datasets/johnsonhk88"
# Install deepeval package
!pip install deepeval  --no-index --no-deps --find-links=file:////{install_DIR}/deepeval-4-0-2/deepeval-package/deepeval-4.0.2-py3-none-any.whl
!pip install portalocker --no-index --no-deps --find-links=file:////{install_DIR}/deepeval-4-0-2/deepeval-package/portalocker-3.2.0-py3-none-any.whl
!pip install posthog --no-index --no-deps --find-links=file:////{install_DIR}/deepeval-4-0-2/deepeval-package/posthog-7.15.0-py3-none-any.whl
!pip install pyfiglet --no-index --no-deps --find-links=file:////{install_DIR}/deepeval-4-0-2/deepeval-package/pyfiglet-1.0.4-py3-none-any.whl

# Install Mlflow
!pip install mlflow --no-index --no-deps --find-links=file:////{install_DIR}/mlflow/mlflow-package/mlflow-3.12.0-py3-none-any.whl
!pip install mlflow_skinny --no-index --no-deps --find-links=file:////{install_DIR}/mlflow/mlflow-package/mlflow_skinny-3.12.0-py3-none-any.whl
!pip install mlflow_tracing --no-index --no-deps --find-links=file:////{install_DIR}/mlflow/mlflow-package/mlflow_tracing-3.12.0-py3-none-any.whl
!pip install databricks-sdk --no-index --no-deps --find-links=file:////{install_DIR}/mlflow/mlflow-package/databricks_sdk-0.110.0-py3-none-any.whl

# !pip install --no-build-isolation -q "mamba-ssm>=2.2" causal-conv1d
!pip install causal-conv1d  --no-index --no-deps --find-links=file:////kaggle/input/datasets/grooking/mamba-ssm/causal_conv1d-1.6.1-cp312-cp312-linux_x86_64.whl
!pip install mamba-ssm  --no-index --no-deps --find-links=file:////kaggle/input/datasets/grooking/mamba-ssm/mamba_ssm-2.3.1-cp312-cp312-linux_x86_64.whl

!pip install bitsandbytes --no-index --no-deps --find-links=file:////{install_DIR}/bitsandbytes/bitsandbytes-package/bitsandbytes-0.48.0-py3-none-manylinux_2_24_x86_64.whl
!pip install trl --no-index --no-deps --find-links=file:////{install_DIR}/trl-transformers-reinforcement-learning/trl-package/trl-1.2.0-py3-none-any.whl

!pip install unsloth --no-index --no-deps --find-links=file:////{install_DIR}/unsloth/unsloth-package/unsloth-2026.5.5-py3-none-any.whl
!pip install unsloth-zoo  --no-index   --no-deps  --find-links=file:////{install_DIR}/unsloth/unsloth-package/unsloth_zoo-2026.5.5-py3-none-any.whl

!pip install xformers   --no-index --no-deps  --find-links=file:////{install_DIR}/xformers/xformers-package/xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl
!pip install flash-attn  --no-index --no-deps  --find-links=file:////kaggle/input/datasets/rezaazami/flash-attn-2-torch210-h100/flash_attn-2.8.4-cp312-cp312-linux_x86_64.whl

Looking in links: file:////kaggle/input/datasets/johnsonhk88/deepeval-4-0-2/deepeval-package/deepeval-4.0.2-py3-none-any.whl
Processing //kaggle/input/datasets/johnsonhk88/deepeval-4-0-2/deepeval-package/deepeval-4.0.2-py3-none-any.whl
Installing collected packages: deepeval
Successfully installed deepeval-4.0.2
Looking in links: file:////kaggle/input/datasets/johnsonhk88/deepeval-4-0-2/deepeval-package/portalocker-3.2.0-py3-none-any.whl
Processing //kaggle/input/datasets/johnsonhk88/deepeval-4-0-2/deepeval-package/portalocker-3.2.0-py3-none-any.whl
Installing collected packages: portalocker
Successfully installed portalocker-3.2.0
Looking in links: file:////kaggle/input/datasets/johnsonhk88/deepeval-4-0-2/deepeval-package/posthog-7.15.0-py3-none-any.whl
Processing //kaggle/input/datasets/johnsonhk88/deepeval-4-0-2/deepeval-package/posthog-7.15.0-py3-none-any.whl
Installing collected packages: posthog
Successfully installed posthog-7.15.0
Looking in links: file:////kaggle/input/datasets/johnsonhk88/deepeval-4-0-2/deepeval-package/pyfiglet-1.0.4-py3-none-any.whl
Processing //kaggle/input/datasets/johnsonhk88/deepeval-4-0-2/deepeval-package/pyfiglet-1.0.4-py3-none-any.whl
Installing collected packages: pyfiglet
Successfully installed pyfiglet-1.0.4
Looking in links: file:////kaggle/input/datasets/johnsonhk88/mlflow/mlflow-package/mlflow-3.12.0-py3-none-any.whl
Processing //kaggle/input/datasets/johnsonhk88/mlflow/mlflow-package/mlflow-3.12.0-py3-none-any.whl
Installing collected packages: mlflow
Successfully installed mlflow-3.12.0
Looking in links: file:////kaggle/input/datasets/johnsonhk88/mlflow/mlflow-package/mlflow_skinny-3.12.0-py3-none-any.whl
Processing //kaggle/input/datasets/johnsonhk88/mlflow/mlflow-package/mlflow_skinny-3.12.0-py3-none-any.whl
Installing collected packages: mlflow_skinny
Successfully installed mlflow_skinny-3.12.0
Looking in links: file:////kaggle/input/datasets/johnsonhk88/mlflow/mlflow-package/mlflow_tracing-3.12.0-py3-none-any.whl
Processing //kaggle/input/datasets/johnsonhk88/mlflow/mlflow-package/mlflow_tracing-3.12.0-py3-none-any.whl
Installing collected packages: mlflow_tracing
Successfully installed mlflow_tracing-3.12.0
Looking in links: file:////kaggle/input/datasets/johnsonhk88/mlflow/mlflow-package/databricks_sdk-0.110.0-py3-none-any.whl
Processing //kaggle/input/datasets/johnsonhk88/mlflow/mlflow-package/databricks_sdk-0.110.0-py3-none-any.whl
Installing collected packages: databricks-sdk
Successfully installed databricks-sdk-0.110.0
Looking in links: file:////kaggle/input/datasets/grooking/mamba-ssm/causal_conv1d-1.6.1-cp312-cp312-linux_x86_64.whl
Processing //kaggle/input/datasets/grooking/mamba-ssm/causal_conv1d-1.6.1-cp312-cp312-linux_x86_64.whl
Installing collected packages: causal-conv1d
Successfully installed causal-conv1d-1.6.1
Looking in links: file:////kaggle/input/datasets/grooking/mamba-ssm/mamba_ssm-2.3.1-cp312-cp312-linux_x86_64.whl
Processing //kaggle/input/datasets/grooking/mamba-ssm/mamba_ssm-2.3.1-cp312-cp312-linux_x86_64.whl
Installing collected packages: mamba-ssm
Successfully installed mamba-ssm-2.3.1
Looking in links: file:////kaggle/input/datasets/johnsonhk88/bitsandbytes/bitsandbytes-package/bitsandbytes-0.48.0-py3-none-manylinux_2_24_x86_64.whl
Processing //kaggle/input/datasets/johnsonhk88/bitsandbytes/bitsandbytes-package/bitsandbytes-0.48.0-py3-none-manylinux_2_24_x86_64.whl
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.48.0
Looking in links: file:////kaggle/input/datasets/johnsonhk88/trl-transformers-reinforcement-learning/trl-package/trl-1.2.0-py3-none-any.whl
Processing //kaggle/input/datasets/johnsonhk88/trl-transformers-reinforcement-learning/trl-package/trl-1.2.0-py3-none-any.whl
Installing collected packages: trl
Successfully installed trl-1.2.0
Looking in links: file:////kaggle/input/datasets/johnsonhk88/unsloth/unsloth-package/unsloth-2026.5.5-py3-none-any.whl
Processing //kaggle/input/datasets/johnsonhk88/unsloth/unsloth-package/unsloth-2026.5.5-py3-none-any.whl
Installing collected packages: unsloth
Successfully installed unsloth-2026.5.5
Looking in links: file:////kaggle/input/datasets/johnsonhk88/unsloth/unsloth-package/unsloth_zoo-2026.5.5-py3-none-any.whl
Processing //kaggle/input/datasets/johnsonhk88/unsloth/unsloth-package/unsloth_zoo-2026.5.5-py3-none-any.whl
Installing collected packages: unsloth-zoo
Successfully installed unsloth-zoo-2026.5.5
Looking in links: file:////kaggle/input/datasets/johnsonhk88/xformers/xformers-package/xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl
Processing //kaggle/input/datasets/johnsonhk88/xformers/xformers-package/xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl
Installing collected packages: xformers
Successfully installed xformers-0.0.35
Looking in links: file:////kaggle/input/datasets/rezaazami/flash-attn-2-torch210-h100/flash_attn-2.8.4-cp312-cp312-linux_x86_64.whl
Processing //kaggle/input/datasets/rezaazami/flash-attn-2-torch210-h100/flash_attn-2.8.4-cp312-cp312-linux_x86_64.whl
Installing collected packages: flash-attn
Successfully installed flash-attn-2.8.4

In [2]:
# !pip install posthog==7.15.0
# !pip install portalocker==3.2.0
# !pip install pyfiglet==1.0.4
# !pip install databricks-sdk==0.110.0

In [3]:
# !pip install -q triton
# !pip install --no-build-isolation -q "mamba-ssm>=2.2" causal-conv1d

In [4]:
import triton
import mamba_ssm
import bitsandbytes

print(triton.__version__)
print(mamba_ssm.__version__)
print(bitsandbytes.__version__)

3.6.0
2.3.1
0.48.0

In [5]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
# import deepeval
import mlflow

In [6]:
# from deepeval.metrics import GEval                     # ← Only this is needed
# from deepeval.test_case import LLMTestCase
# from deepeval import evaluate

In [7]:
# from trl import DPOTrainer, DPOConfig
# from peft import PeftModel, LoraConfig
# from datasets import load_dataset
# import torch

import os, glob, sys, subprocess, site, importlib.util, shutil, stat, types, re

import datasets
import kagglehub

import torch
# import mamba_ssm later

from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import LoraConfig, get_peft_model, TaskType, PeftModel
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from trl import SFTTrainer, SFTConfig
from trl import GRPOConfig, GRPOTrainer
from unsloth import FastLanguageModel

import pandas as pd
import random
import gc, time

import json, zipfile

/usr/local/lib/python3.12/dist-packages/unsloth/__init__.py:144: UserWarning: WARNING: Unsloth should be imported before [trl, transformers, peft] to ensure all optimizations are applied. Your code may run slower or encounter memory issues without these optimizations.

Please restructure your imports with 'import unsloth' at the top of your file.
  from ._gpu_init import *

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!

In [8]:
import pandas as pd
import torch
import gc
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, PeftModel
from typing import Optional, Tuple, Dict


import kagglehub
# import mamba_ssm
# from trl import GRPOConfig, GRPOTrainer

In [9]:
import numpy as np
from sklearn.metrics import f1_score, recall_score, precision_score

In [10]:
class CFG:
    trainFile = "/kaggle/input/competitions/nvidia-nemotron-model-reasoning-challenge/train.csv"
    testFile = "/kaggle/input/competitions/nvidia-nemotron-model-reasoning-challenge/test.csv"
    cotFile = "/kaggle/input/datasets/johnsonhk88/nemotron-model-reasoning-challenge-generate-cot/train_cot2.csv"
    llmModel1 = "/kaggle/input/models/metric/nemotron-3-nano-30b-a3b-bf16/transformers/default/1"
    cotModel1 = "/kaggle/input/models/johnsonhk88/nvidia-nemotron-model-sft-cot-fine-tuning/transformers/default/1"

    USE_COT = True  # use Generative Chain of Thought Dataset for training
    MAX_COT_PROMPT_LEN = 2048   #1600  #3072 #4000 # avoid , too large window lenght for traing, OOM GPU VRAM   
    # Enable Supervised Fine Tuning or Enable GRPO 
    SFT =  False #True #True
    GRPO = False #False
    MIX_SFT_GRPO = True

In [11]:
mlflow_local= True # suitable for kaggle envirorment
# OUTPUT_DIR = "./model-finetuned"
MLFLOW_EXPERIMENT = "Nemoton-Reasoning-Fine-Tuning"


if mlflow_local:
    mlflowUrl = "sqlite:///mlflow.db" # for local sqlite db (recommend)
    # mlflowUrl = "file:///mlruns" # for local file 

else:
    # localhost
    mlflowUrl = "http://localhost:5000"




def setup_mlflow_run(
    experiment_name: str = "wonderland_nemotron_reasoning",
    run_name_suffix: str = "",
    train: bool = True
):
    """
    Separate MLflow setup function.
    Sets tracking URI, experiment, starts a run, and returns the active run context.
    """
    # project setup
    mlflow.set_tracking_uri(mlflowUrl)
    mlflow.set_experiment(experiment_name)

    # === CRITICAL: End any previously active run to prevent conflict ===
    try:
        mlflow.end_run()          # safely ends any lingering run
    except:
        pass                      # no active run → ignore
    
    run_name = f"eval_{run_name_suffix}"
    run = mlflow.start_run(run_name=run_name)
    print(f"MLflow run started: {run_name} (ID: {run.info.run_id})")
    return run

    if train:
        run_name = f"train_{run_name_suffix}"
    else:
        run_name = f"eval_{run_name_suffix}"
    run = mlflow.start_run(run_name=run_name)
    print(f"MLflow run started: {run_name} (ID: {run.info.run_id})")
    return run

In [12]:
def clearMemory():
    for _ in range(5):
        torch.cuda.empty_cache()
        gc.collect()
        time.sleep(0.3)

In [13]:
clearMemory()

## Load Dataset

In [15]:

# ====================== DATASET LOADING ======================
def load_train_data() -> pd.DataFrame:
    """Load the full training dataset (train.csv)"""
    if CFG.USE_COT:
        df = pd.read_csv(CFG.cotFile)

        # === Filter only rows with valid CoT reasoning ===
        df = df[df["cot_reasoning"].notna() & (df["cot_reasoning"].str.strip() != "")]
        # === Keep only HIGH-QUALITY SHORT CoT ===
        # df = df[df['cot_reasoning'].str.len() < 2448]                    # Short CoT only
        df = df[df['cot_reasoning'].str.len() < 3500]
        df = df[~df['cot_reasoning'].str.contains("Unable to generate|Failed after|Error", case=False)]
        df = df.reset_index(drop=True)
        print(f"Total rows after filtering: {len(df)}")

    else:
        df = pd.read_csv(CFG.trainFile)
    print(f"✅ Loaded train dataset: {len(df):,} examples")
    return df


def load_val_data(val_size: int = 400) -> pd.DataFrame:
    """Load a fixed validation split from train.csv (same samples every run)"""
    train_df = load_train_data()
    if val_size > len(train_df):
        print(f"⚠️  Requested val_size ({val_size}) > available data. Using all {len(train_df)} samples.")
        val_size = len(train_df)
    val_df = train_df.sample(n=val_size, random_state=42).reset_index(drop=True)
    print(f"✅ Created fixed validation split: {len(val_df)} examples")
    return  train_df , val_df


def load_test_data() -> pd.DataFrame:
    """Load the official test dataset (test.csv) for final inference"""
    df = pd.read_csv(CFG.testFile)
    print(f"✅ Loaded test dataset: {len(df)} examples")
    return df

In [16]:
trainDF, valDF = load_val_data(200)

Total rows after filtering: 2111
✅ Loaded train dataset: 2,111 examples
✅ Created fixed validation split: 200 examples

In [17]:
# trainDF
valDF

,id,prompt,answer,cot_reasoning
0,2e5e7fe7,"In Alice's Wonderland, a secret bit manipulati...",01101101,<think>\nThe user wants me to find a hidden bi...
1,ad789984,"In Alice's Wonderland, numbers are secretly co...",XLIV,<think>\nThe user wants me to identify the tra...
2,274def88,"In Alice's Wonderland, a secret set of transfo...",92,<think>\nHere's a thinking process:\n\n1. **A...
3,2d63b436,"In Alice's Wonderland, a secret bit manipulati...",00010000,<think>\nThe user wants me to find a hidden bi...
4,0e700e9d,"In Alice's Wonderland, numbers are secretly co...",LXIX,<think>\nThe user wants me to explain the thou...
...,...,...,...,...
195,23c59364,"In Alice's Wonderland, a secret set of transfo...",>/,<think>\nHere's a thinking process:\n\n1. **A...
196,7877dd7f,"In Alice's Wonderland, a secret bit manipulati...",11101000,<think>\nThe user wants me to find a transform...
197,6a578940,"In Alice's Wonderland, a secret bit manipulati...",10010000,<think>\nThe user wants me to find a hidden bi...
198,9f95886e,"In Alice's Wonderland, numbers are secretly co...",II,<think>\nThe user wants me to identify the tra...
199,33519c2f,"In Alice's Wonderland, a secret bit manipulati...",00010000,<think>\nThe user wants me to find a hidden bi...

In [18]:
testDF =  load_test_data()
testDF

✅ Loaded test dataset: 3 examples

         id                                             prompt
0  00066667  In Alice's Wonderland, a secret bit manipulati...
1  000b53cf  In Alice's Wonderland, a secret bit manipulati...
2  00189f6a  In Alice's Wonderland, secret encryption rules...

In [19]:
trainDF

,id,prompt,answer,cot_reasoning
0,00066667,"In Alice's Wonderland, a secret bit manipulati...",10010111,<think>\nHere's a thinking process that leads ...
1,000b53cf,"In Alice's Wonderland, a secret bit manipulati...",01000011,<think>\nThe user wants me to solve a puzzle b...
2,00189f6a,"In Alice's Wonderland, secret encryption rules...",cat imagines book,<think>\nThe user wants me to explain the proc...
3,001b24c4,"In Alice's Wonderland, numbers are secretly co...",XXXVIII,<think>\nThe user wants me to identify the hid...
4,00208201,"In Alice's Wonderland, a secret unit conversio...",16.65,<think>\nThe user wants me to solve a specific...
...,...,...,...,...
2106,c5326116,"In Alice's Wonderland, numbers are secretly co...",LXIX,<think>\nThe user wants me to identify the tra...
2107,c54765cd,"In Alice's Wonderland, a secret bit manipulati...",00011110,<think>\nThe user wants me to find a transform...
2108,c5842a35,"In Alice's Wonderland, numbers are secretly co...",XVI,<think>\nThe user wants me to identify the tra...
2109,c58451f9,"In Alice's Wonderland, a secret bit manipulati...",10010100,<think>\nThe user wants me to find a transform...
2110,c5bd62f6,"In Alice's Wonderland, numbers are secretly co...",XI,<think>\nThe user wants me to identify a trans...

In [20]:
trainDF['cot_len'] = trainDF['cot_reasoning'].str.len()

In [21]:
trainDF.cot_len.describe()

count    2111.000000
mean     1551.675509
std      1318.221127
min       154.000000
25%       329.000000
50%       757.000000
75%      3064.000000
max      3499.000000
Name: cot_len, dtype: float64

In [23]:
(trainDF.cot_len> 3400).sum()

np.int64(175)

# Load Model

In [24]:
BASE_MODEL_PATH = kagglehub.model_download("metric/nemotron-3-nano-30b-a3b-bf16/transformers/default")
BASE_MODEL_PATH

'/kaggle/input/models/metric/nemotron-3-nano-30b-a3b-bf16/transformers/default/1'

In [27]:
UNSLOTH_VERSION = True
MAX_SEQ_LENGTH = 5000  #3800 #4096 #8192 # 4096
LOAD_IN_4BIT = False

In [28]:
if UNSLOTH_VERSION:
    def load_model(
        model_name: str,
        adapter_path: Optional[str] = None
    ) -> Tuple[AutoModelForCausalLM, AutoTokenizer]:
        print(f"Loading unsloth model: {model_name} {'+ adapter: ' + adapter_path if adapter_path else '(base)'}")    
        model, tokenizer = FastLanguageModel.from_pretrained(
            model_name=model_name,
            max_seq_length=MAX_SEQ_LENGTH,
            load_in_4bit=LOAD_IN_4BIT,
            load_in_8bit=False,
            full_finetuning=False,
            trust_remote_code=True,
            unsloth_force_compile=False,
            attn_implementation="eager",
            # attn_implementation= "flash_attention_2", # Memotron not support
            dtype=torch.bfloat16,
            local_files_only=True,                 # ← Important: faster loading from Kaggle input
            low_cpu_mem_usage=False,
        )

        model = FastLanguageModel.get_peft_model(
            model,
            r=16,
            lora_alpha=32,
            target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
            lora_dropout= 0.0, #0.05,
            bias="none",
            use_gradient_checkpointing="unsloth", #"unsloth",   # Best for memory + stability
            random_state=42,
        )
        model.print_trainable_parameters()
        return model, tokenizer
        
else:
    def load_model(
        model_name: str,
        adapter_path: Optional[str] = None
    ) -> Tuple[AutoModelForCausalLM, AutoTokenizer]:
        """Load base model + optional LoRA adapter."""
        print(f"Loading model: {model_name} {'+ adapter: ' + adapter_path if adapter_path else '(base)'}")
        
        # === Model + LoRA (Mamba/MoE stable config) ===
        # bnb_config = BitsAndBytesConfig(
        #     load_in_4bit=True,                    # ← Change from 8-bit to 4-bit
        #     bnb_4bit_quant_type="nf4",            # nf4 is best for most models
        #     bnb_4bit_use_double_quant=True,       # Saves extra memory + more stable
        #     bnb_4bit_compute_dtype=torch.bfloat16,  # or torch.float16
        # )
        # === Model + LoRA (8-bit + smaller rank = stable for Mamba) ===
        # bnb_config = BitsAndBytesConfig(
        #     load_in_8bit=True,                    # ← Changed to 8-bit (more stable)
        #     # bnb_4bit_compute_dtype=torch.bfloat16,
        #     bnb_4bit_compute_dtype=torch.float16,
        # )
    
        model = AutoModelForCausalLM.from_pretrained(
            model_name,
            # quantization_config=bnb_config,
            device_map="auto",
            trust_remote_code=True,
            dtype=torch.bfloat16,
            # dtype=torch.float16 # for 8bit
        )
    
        if adapter_path:
            model = PeftModel.from_pretrained(model, adapter_path)
    
        tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token

        print("LoRA Configure")
        lora_config = LoraConfig(
            r=16,
            lora_alpha=32,
            target_modules=["q_proj","k_proj","v_proj","o_proj","gate_proj","up_proj","down_proj"],
            lora_dropout=0.05,
            bias="none",
            task_type="CAUSAL_LM")
        model = get_peft_model(model, lora_config)
        model.print_trainable_parameters()
    
        return model, tokenizer

## Load base model

In [29]:

# del model
# del tokenizer

In [30]:
clearMemory()

In [31]:
if CFG.SFT:
    model, tokenizer = load_model(BASE_MODEL_PATH, None)

## Evaluation function

In [32]:
import re
import difflib



import re

if 0 : #CFG.USE_COT:
    def extract_final_answer(text: str) -> str:
        """
        Extract the final answer from the model's output.
        Priority order:
        1. Content inside \boxed{}
        2. Content after </think> tag (if exists)
        3. Last meaningful line (fallback)
        """
        if not text or not isinstance(text, str):
            return ""
    
        text = text.strip()
    
        # === 1. Highest priority: Extract from \boxed{} ===
        boxed_match = re.search(r'\\boxed\{(.*?)\}', text, re.DOTALL)
        if boxed_match:
            answer = boxed_match.group(1).strip()
            # Clean common artifacts
            answer = re.sub(r'\s+', ' ', answer)  # collapse multiple spaces
            return answer
    
        # === 2. If model used <think>, take everything after </think> ===
        if '</think>' in text:
            after_think = text.split('</think>')[-1].strip()
            
            # Try to find \boxed{} after thinking
            boxed_match = re.search(r'\\boxed\{(.*?)\}', after_think, re.DOTALL)
            if boxed_match:
                return boxed_match.group(1).strip()
            
            # Otherwise, take the last non-empty line after </think>
            lines = [line.strip() for line in after_think.split('\n') if line.strip()]
            if lines:
                return lines[-1]
    
        # === 3. Fallback: Take the last meaningful line ===
        lines = [line.strip() for line in text.split('\n') if line.strip()]
        if lines:
            last_line = lines[-1]
            
            # Remove common prefixes the model sometimes adds
            prefixes_to_remove = [
                "the answer is", "answer:", "final answer:", 
                "the final answer is", "so the answer is"
            ]
            for prefix in prefixes_to_remove:
                if last_line.lower().startswith(prefix):
                    last_line = last_line[len(prefix):].strip()
                    break
            
            return last_line
    
        # Last resort
        return text.strip()

else:

    def extract_final_answer(text: str) -> str:
        """
        Robust extraction for Nemotron 3 with <think> support.
        Priority:
        1. Content inside \boxed{}
        2. Content after </think>
        3. Last meaningful line
        """
        if not text or not isinstance(text, str):
            return ""
        
        text = text.strip()
        
        # Priority 1: Extract from \boxed{}
        match = re.search(r'\\boxed\{([^}]+)\}', text)
        if match:
            return match.group(1).strip()
        
        # Priority 2: Extract after </think>
        if '</think>' in text:
            after_think = text.split('</think>')[-1].strip()
            # Clean special tokens
            after_think = re.sub(r'<\|im_end\|>|<\|im_start\|>|<\|im_start\|>assistant', '', after_think).strip()
            if after_think:
                return after_think
        
        # Priority 3: Remove thinking block and take last line
        if '<think>' in text:
            # Remove everything inside <think> ... </think>
            text = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL)
        
        # Take last non-empty line
        lines = [line.strip() for line in text.split('\n') if line.strip()]
        if lines:
            # Clean common prefixes
            last_line = re.sub(r'^(output|answer|final answer)[:\s]*', '', lines[-1], flags=re.IGNORECASE)
            return last_line.strip()
        
        return text.strip()

In [33]:
if 0: #CFG.USE_COT:
    def is_correct(pred: str, gt: str) -> float:
        """Compare prediction with ground truth (normalized exact match)."""
        if not pred or not gt:
            return 0.0
    
        pred_clean = str(pred).lower().strip()
        gt_clean = str(gt).lower().strip()
    
        # Remove common artifacts
        for token in ["<|im_end|>", "<|im_start|>", "</s>", "\\boxed{", "}", "<think>", "</think>"]:
            pred_clean = pred_clean.replace(token, " ")
            gt_clean = gt_clean.replace(token, " ")
    
        pred_clean = " ".join(pred_clean.split())
        gt_clean = " ".join(gt_clean.split())
    
        return 1.0 if pred_clean == gt_clean else 0.0

else:

    def is_correct(pred: str, gt: str, tolerance: float = 0.01) -> float:
        pred = pred.strip().lower()
        gt = gt.strip().lower()
        
        if pred == gt:
            return 1.0
        
        # Numerical tolerance
        try:
            p = float(pred)
            g = float(gt)
            if g == 0:
                return 1.0 if abs(p) < tolerance else 0.0
            return 1.0 if abs(p - g) / abs(g) <= tolerance else 0.0
        except:
            pass
        
        # String similarity fallback
        similarity = difflib.SequenceMatcher(None, pred, gt).ratio()
        return 1.0 if similarity > 0.92 else 0.0

In [34]:
if 0:
    def run_evaluation(
    model,
    tokenizer,
    val_size: int = 400,
    experiment_name: str = "wonderland_nemotron_reasoning",
    run_name_suffix: str = ""
) -> Dict:
    
        run = setup_mlflow_run(experiment_name, run_name_suffix)
        mlflow.log_param("val_size", val_size)
        mlflow.log_param("generation_method", "CoT_prompt + greedy + extract_final_answer")
    
        exact_matches = []
        start_time = time.time()
    
        print(f"Running evaluation on {val_size} samples using CoT-style prompt...\n")
    
        if UNSLOTH_VERSION:
            FastLanguageModel.for_inference(model)
    
        for idx, row in enumerate(valDF.iterrows(), start=1):
            _, row = row
            prompt = row['prompt']
            gt = str(row['answer']).strip()
    
            print(f"Eval Sample: {idx}")
    
            # ====================== CoT-ALIGNED PROMPT ======================
            full_prompt = f"""<|system|>You are an expert at discovering hidden transformation rules in Alice's Wonderland puzzles.

First, think step by step inside <think> </think> tags.
After you finish thinking, output ONLY the final answer inside \\boxed{{}}.
Do not add any text before or after the boxed answer.</s>
<|user|>{prompt}
<|assistant|>"""
    
            # Tokenize
            tokenized = tokenizer(
                full_prompt,
                return_tensors="pt",
                add_special_tokens=True
            )
            input_ids = tokenized.input_ids.to(model.device)
            input_len = input_ids.shape[-1]
            attention_mask = tokenized.attention_mask.to(model.device)
    
            # Generate
            outputs = model.generate(
                input_ids,
                attention_mask=attention_mask,
                max_new_tokens=512,           # Increased for reasoning
                do_sample=False,
                num_beams=1,
                eos_token_id=tokenizer.eos_token_id,
                pad_token_id=tokenizer.pad_token_id,
            )
    
            # Decode only generated tokens
            generated_tokens = outputs[0][input_len:]
            raw_output = tokenizer.decode(generated_tokens, skip_special_tokens=False)
    
            # Clean special tokens
            for token in ["<|im_end|>", "<|im_start|>", "</s>", "<|assistant|>"]:
                raw_output = raw_output.replace(token, "").strip()
    
            # Extract final answer
            pred = extract_final_answer(raw_output)
    
            # Compare
            is_exact = is_correct(pred, gt)
            exact_matches.append(is_exact)
    
            print(f"Exact ans : {gt}")
            print(f"Pred ans  : {pred}")
            print(f"Match     : {is_exact}")
            print("-" * 50)
    
            if idx % 10 == 0:
                print(f"Processed {idx} samples...")
    
            if idx >= val_size:
                break
    
        # ====================== FINAL METRICS ======================
        avg_exact_match = sum(exact_matches) / len(exact_matches)
        mlflow.log_metric("exact_match", avg_exact_match)
        mlflow.log_metric("eval_time_sec", time.time() - start_time)
        mlflow.log_metric("samples_evaluated", len(exact_matches))
    
        print("\n" + "=" * 65)
        print(f"=== EVALUATION RESULTS (on {len(exact_matches)} samples) ===")
        print(f"Exact Match Accuracy: {avg_exact_match:.4f} "
              f"({sum(exact_matches)} / {len(exact_matches)})")
        print("=" * 65)
    
        mlflow.end_run()
    
        return {
            "exact_match": avg_exact_match,
            "samples_used": len(exact_matches)
        }
else:
    def run_evaluation(
        model,
        tokenizer,
        val_size: int = 400,
        experiment_name: str = "wonderland_nemotron_reasoning",
        run_name_suffix: str = ""
    ) -> Dict:
        run = setup_mlflow_run(experiment_name, run_name_suffix)
    
        mlflow.log_param("val_size", val_size)
        mlflow.log_param("generation_method", "apply_chat_template + greedy_generate")
    
        test_cases = []
        exact_matches = []
        start_time = time.time()
    
        print(f"Running evaluation on {val_size} samples using direct generate...")
    
        if UNSLOTH_VERSION:
            FastLanguageModel.for_inference(model)
        for idx, row in enumerate(valDF.iterrows(), start=1):
            _, row = row  # unpack
            prompt = row['prompt']
            gt = str(row['answer']).strip()
    
            print(f"Eval Sample: {idx}")
            
            full_prompt = f"""<|system|>You are an expert at discovering hidden transformation rules in Alice's Wonderland puzzles.
    Analyze the examples carefully and determine the hidden rule.
    **Output ONLY the final answer inside \\boxed{{}}.**
    Do not explain your reasoning. Do not write any text before or after the boxed answer.
    <|user|>{prompt}
    <|assistant|>"""
    
            # messages = [
            #     {"role": "system", "content": "You are an expert at discovering hidden transformation rules in Alice's Wonderland puzzles. Analyze the examples carefully and output ONLY the final answer."},
            #     {"role": "user", "content": prompt}
            # ]
            # messages = [
            #     {
            #         "role": "system",
            #         "content": "You are an expert at discovering hidden transformation rules in Alice's Wonderland puzzles. "
            #                    "Analyze the examples carefully, but output ONLY the final answer. "
            #                    "Do NOT explain, do NOT show reasoning, do NOT write 'the answer is', "
            #                    "do NOT add any text before or after the answer. Just output the result."
            #     },
            #     {"role": "user", "content": prompt}
            # ]
            
            # full_prompt = tokenizer.apply_chat_template(
            #     messages,
            #     tokenize=False,
            #     add_generation_prompt=True,
            #     # return_tensors="pt"
            #     # enable_thinking=enable_thinking
            # )
            
            # Tokenize as string → tensor
            tokenized = tokenizer(
                full_prompt,
                return_tensors="pt",
                add_special_tokens=True
            )
    
            input_ids = tokenized.input_ids.to(model.device)
            input_len = tokenized["input_ids"].shape[-1]
            attention_mask = tokenized.attention_mask.to(model.device)
    
            # === Generate ===
            outputs = model.generate(
                input_ids,
                attention_mask=attention_mask,
                max_new_tokens=512,
                do_sample=False,
                num_beams=1,
                eos_token_id=tokenizer.eos_token_id,
                pad_token_id=tokenizer.pad_token_id,
            )
            
            # === CLEAN DECODING (new) ===
            generated_tokens = outputs[0][input_len:]
            full_output = tokenizer.decode(generated_tokens, skip_special_tokens=False)
            
            # Extract only assistant response
            if "<|assistant|>" in full_output:
                raw_pred = full_output.split("<|assistant|>")[-1]
            else:
                raw_pred = full_output
            
            # Clean special tokens
            special_tokens = ["<|im_end|>", "<|im_start|>", "<|im_start|>assistant", "</s>"]
            for token in special_tokens:
                raw_pred = raw_pred.replace(token, "").strip()
            
            # === Use robust extraction (supports <think> and \boxed{}) ===
            pred = extract_final_answer(raw_pred)
            
            # pred = pred.strip()   # final clean
            print(f"Exact ans: {gt.lower().strip()}")
            print(f"Pred ans: { pred.lower().strip()}\n")
            
    
            # is_exact = 1.0 if pred.lower().strip() == gt.lower().strip() else 0.0
            # exact_matches.append(is_exact)
            # Then in the loop:
            is_exact = is_correct(pred, gt)
            exact_matches.append(is_exact)
            print(f"Matches = {is_exact}")
            print("-"*20)
    
            # test_case = LLMTestCase(input=prompt, actual_output=pred, expected_output=gt)
            # test_cases.append(test_case)
    
            if idx % 5 == 0 or idx == len(valDF):
                print(f"   Processed {idx}  samples...")
            
            if idx>= val_size:
                break
            
    
        # Metrics
        avg_exact_match = sum(exact_matches) / val_size
        mlflow.log_metric("exact_match", avg_exact_match)
        mlflow.log_metric("eval_time_sec", time.time() - start_time)
        mlflow.log_metric("samples_evaluated", val_size)
    
        
    
        print(f"\n=== EVALUATION RESULTS ===")
        # print(f"Exact Match (manual):       {avg_exact_match:.4f}")
        # print(f"DeepEval Correctness:       {results[0].score:.4f}")
        # print(f"DeepEval Rule Quality:      {results[1].score:.4f}")
        # print(f"Evaluation time:            {time.time() - start_time:.1f} seconds")
        print(f"\n=== EVALUATION RESULTS (on exactly {len(valDF)} samples) ===")
        print(f"Exact Match Accuracy: {avg_exact_match:.4f} ({int(avg_exact_match*val_size)}/{val_size})")
        mlflow.end_run()
    
        return {
            # "exact_match": avg_exact_match,
            # "deepeval_correctness": results[0].score,
            # "deepeval_rule_quality": results[1].score,
            "exact_match": avg_exact_match,
            "samples_used": val_size
        }

In [35]:
def evaluate_model(
    # model_name: str,
    # adapter_path: Optional[str] = None,
    model,
    tokenizer,
    val_size: int = 400,
    experiment_name: str = "wonderland_nemotron_reasoning",
    suffix= "base"
):
    """Convenience wrapper"""
    return run_evaluation(model, tokenizer, val_size, experiment_name, run_name_suffix=suffix)

## Evaluate base model

In [36]:
if 0: #CFG.SFT:
    evaluate_model(
        # model_name= BASE_MODEL_PATH,
        model,
        tokenizer,
        val_size=10
    )

In [37]:
experiments = mlflow.search_experiments()
for exp in experiments:
    print(f"Experiment ID: {exp.experiment_id}, Name: {exp.name}")

2026/06/14 12:21:01 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/06/14 12:21:01 INFO mlflow.store.db.utils: Updating database tables

Experiment ID: 0, Name: Default

In [38]:
# baseEvalRet = mlflow.search_runs(experiment_ids=["1"])
baseEvalRet = mlflow.search_runs(search_all_experiments=True)
baseEvalRet

Empty DataFrame
Columns: [run_id, experiment_id, status, artifact_uri, start_time, end_time]
Index: []

# Single Test for debug

In [39]:
# testPrompt = valDF.iloc[0]["prompt"]
# testAns = valDF.iloc[0]["answer"]
# testPrompt

In [40]:

# full_prompt = f"""<|system|>You are an expert at discovering hidden transformation rules in Alice's Wonderland puzzles.
# You MUST output ONLY the final answer. Do not explain, do not show reasoning, do not write "the answer is", do not add any text before or after the answer.
# <|user|>{testPrompt}
# <|assistant|>"""
# prompt = full_prompt

In [41]:
# messages = [
#             {"role": "system", "content": "You are an expert at discovering hidden transformation rules in Alice's Wonderland puzzles. Analyze the examples carefully and output ONLY the final answer."},
#             {"role": "user", "content": testPrompt}
#         ]

# prompt = tokenizer.apply_chat_template(
#     messages,
#     tokenize=False,
#     add_generation_prompt=True,
#     # return_tensors="pt"
#     # enable_thinking=enable_thinking
# )
# prompt

In [42]:
# tokenized = tokenizer(
#     prompt,
#     return_tensors="pt",
#     add_special_tokens=True
# )
# input_ids = tokenized.input_ids.to(model.device)
# input_len = tokenized["input_ids"].shape[-1]
# attention_mask = tokenized.attention_mask.to(model.device)

In [43]:

# === Generate ===
# outputs = model.generate(
#     input_ids,
#     attention_mask=attention_mask,
#     max_new_tokens=1024,
#     do_sample=False,
#     num_beams=1,
#     eos_token_id=tokenizer.eos_token_id,
#     pad_token_id=tokenizer.pad_token_id,
# )

In [44]:
# # Decode and extract answer
# === CLEAN DECODING (new) ===
# full_output = tokenizer.decode(outputs[0][input_len:], skip_special_tokens=False)

# # Extract only assistant response
# if "<|assistant|>" in full_output:
#     pred = full_output.split("<|assistant|>")[-1]
# else:
#     pred = full_output

# # Remove common special tokens
# special_tokens = ["<|im_end|>", "<|endoftext|>", "</s>", "<|eot_id|>", "<|im_start|>"]
# for token in special_tokens:
#     pred = pred.replace(token, "").strip()

# pred = pred.strip()   # final clean

In [45]:
# full_output

In [46]:
# pred


### Full SFT (Supervised Fine-Tuning) script for NVIDIA Nemotron challenge.
#### Uses real train.csv + modular functions from evaluation.py

In [47]:
# OUTPUT_ADAPTER = "/kaggle/working/sft_final"
SFT_ADAPTER = "/kaggle/working/sft_final"
OUTPUT_ADAPTER = "/kaggle/working/grpo_final"

In [48]:
# SYSTEM_PROMPT = """You are an expert at discovering hidden transformation rules in Alice's Wonderland puzzles.

# First, think step by step inside <think> </think> tags.
# After you finish thinking, output ONLY the final answer inside \\boxed{}.
# Do not add any text after the boxed answer."""

SYSTEM_PROMPT = """You are an expert at discovering hidden transformation rules in Alice's Wonderland puzzles.

You must follow this exact output format:
1. First, write your step-by-step reasoning inside <think> </think> tags.
2. After finishing your thinking, output ONLY the final answer using this exact format:
\\boxed{answer}

Do not write anything before the <think> tag or after the \\boxed{} answer."""

In [58]:
if CFG.USE_COT:
    def format_sft_example(row):
        prompt = row['prompt']
        answer = str(row['answer']).strip()
        cot = str(row.get('cot_reasoning', '')).strip()
    
        # Clean CoT
        if '<think>' in cot:
            import re
            match = re.search(r'<think>(.*?)</think>', cot, re.DOTALL)
            if match:
                cot = match.group(1).strip()
    
        full_text = f"""{SYSTEM_PROMPT}
    <|user|>{prompt}
    <|assistant|><think>
    {cot}
    </think>
    \\boxed{{{answer}}}"""
    
        # === Smart truncation: keep the end (answer + last part of reasoning) ===
        max_len = 4800 #4400 #5000 #4000 #3500 #3200 #4096
        if len(full_text) > max_len:
            full_text = full_text[-max_len:]   # Keep the last part
    
        return {"text": full_text}

else:
    # add enabling thinking processing
    def format_sft_example(row):
        prompt = row['prompt']
        answer = str(row['answer']).strip()
        
        full_text = f"""{SYSTEM_PROMPT}
    
    <|im_start|>user
    {prompt}<|im_end|>
    <|im_start|>assistant
    <think>
    I need to find the hidden transformation rule...
    </think>
    \\boxed{{{answer}}}<|im_end|>"""
        
        return {"text": full_text}

In [59]:
# === YOUR COMPUTE_METRIC FUNCTION (added here) ===
def compute_metric(eval_pred):
    logits, labels = eval_pred
    
    # Convert to numpy if needed
    if isinstance(logits, torch.Tensor):
        logits = logits.cpu().numpy()
    if isinstance(labels, torch.Tensor):
        labels = labels.cpu().numpy()

    # 1. Overall next-token accuracy (keep for reference)
    shift_logits = logits[..., :-1, :]
    shift_labels = labels[..., 1:]
    preds = np.argmax(shift_logits, axis=-1)
    mask = shift_labels != -100
    token_accuracy = (preds == shift_labels & mask).sum() / mask.sum() if mask.sum() > 0 else 0.0

    # 2. Last-token metrics (much more meaningful for puzzle solving)
    last_logits = logits[:, -1, :]           # shape: (batch, vocab)
    last_labels = labels[:, -1]              # shape: (batch,)
    
    top3_preds = np.argsort(last_logits, axis=-1)[:, -3:]
    match = (top3_preds == last_labels[:, None])
    predictions = top3_preds[:, 2]           # top-1 prediction

    last_token_acc = (predictions == last_labels).mean()

    f1score     = f1_score(last_labels, predictions, average='weighted', zero_division=1)
    recallScore = recall_score(last_labels, predictions, average='weighted', zero_division=1)
    precision   = precision_score(last_labels, predictions, average='weighted', zero_division=1)

    # MAP@3 on last token
    map3 = 0.0
    for i in range(len(last_labels)):
        if match[i, 0]:
            map3 += 1.0
        elif match[i, 1]:
            map3 += 1.0 / 2
        elif match[i, 2]:
            map3 += 1.0 / 3
    map3Score = map3 / len(last_labels)

    return {
        "accuracy": token_accuracy,           # overall next-token (for reference)
        "last_token_accuracy": last_token_acc, # ← most important
        "recall": recallScore,
        "precision": precision,
        "f1-score": f1score,
        "map_3": map3Score
    }

## Create Dataset

In [60]:
# randow sample 
trainDF = trainDF.sample(frac=1, random_state=42).reset_index(drop=True)

In [61]:
# COLS = ['text','a']
dataset = Dataset.from_pandas(trainDF).map(format_sft_example, remove_columns=trainDF.columns.tolist())
dataset

Map:   0%|          | 0/2111 [00:00<?, ? examples/s]

Dataset({
    features: ['text'],
    num_rows: 2111
})

In [62]:
trainDF

,id,prompt,answer,cot_reasoning,cot_len
0,512dd86d,"In Alice's Wonderland, a secret bit manipulati...",00000001,<think>\nThe user wants me to find a hidden bi...,3468
1,0f0536de,"In Alice's Wonderland, a secret set of transfo...",2376,<think>\nThe user wants me to explain how to f...,228
2,05c38073,"In Alice's Wonderland, a secret unit conversio...",15.62,<think>\nThe user wants me to explain how to f...,167
3,724fe70c,"In Alice's Wonderland, numbers are secretly co...",XXXVIII,<think>\nThe user wants me to find the hidden ...,285
4,7877dd7f,"In Alice's Wonderland, a secret bit manipulati...",11101000,<think>\nThe user wants me to find a transform...,3121
...,...,...,...,...,...
2106,00208201,"In Alice's Wonderland, a secret unit conversio...",16.65,<think>\nThe user wants me to solve a specific...,3493
2107,5e0285fc,"In Alice's Wonderland, a secret unit conversio...",14.59,<think>\nThe user wants me to find a hidden tr...,189
2108,71ab0dcb,"In Alice's Wonderland, a secret unit conversio...",18.68,<think>\nHere's a thinking process:\n\n1. **A...,585
2109,73cb93e8,"In Alice's Wonderland, secret encryption rules...",hatter discovers around wonderland,<think>\nThe user wants me to find the hidden ...,332
2110,5e2d5262,"In Alice's Wonderland, secret encryption rules...",bird explores around valley,<think>\nHere's a thinking process:\n\n1. **A...,581

In [63]:
dataset = dataset.map(
    lambda x: {"row_len": [len(text) for text in x["text"]]}, 
    batched=True
)

Map:   0%|          | 0/2111 [00:00<?, ? examples/s]

In [64]:
lengths_series = pd.Series(dataset["row_len"])
print(lengths_series.describe())

count    2111.000000
mean     2306.406442
std      1367.224150
min       766.000000
25%      1070.000000
50%      1496.000000
75%      3911.000000
max      4434.000000
dtype: float64

In [65]:
(lengths_series > 4400).sum()

np.int64(16)

In [66]:

# === CREATE SMALL EVAL SPLIT FOR DEBUGGING ===
eval_size = 100 #200 #50 #200
# eval_dataset = dataset.shuffle(seed=42).select(range(eval_size))
# train_dataset = dataset.shuffle(seed=42).select(range(eval_size, len(dataset)))
# print(f"✅ Train samples: {len(train_dataset)} | Eval samples: {len(eval_dataset)}")

In [67]:
# dataset["train"]
dataset = dataset.train_test_split(test_size=eval_size, seed=42, shuffle=True)
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'row_len'],
        num_rows: 2011
    })
    test: Dataset({
        features: ['text', 'row_len'],
        num_rows: 100
    })
})

In [68]:
print(dataset["train"]["text"][1])

You are an expert at discovering hidden transformation rules in Alice's Wonderland puzzles.

You must follow this exact output format:
1. First, write your step-by-step reasoning inside <think> </think> tags.
2. After finishing your thinking, output ONLY the final answer using this exact format:
\boxed{answer}

Do not write anything before the <think> tag or after the \boxed{} answer.
    <|user|>In Alice's Wonderland, a secret unit conversion is applied to measurements. For example:
38.37 m becomes 25.99
35.56 m becomes 24.09
22.14 m becomes 15.00
41.11 m becomes 27.85
29.11 m becomes 19.72
Now, convert the following measurement: 12.03 m
    <|assistant|><think>
    Here's a thinking process:

1.  **Analyze User Input:**
   - **Context:** Alice's Wonderland puzzle, secret unit conversion.
   - **Examples:**
     - 38.37 m -> 25.99
     - 35.56 m -> 24.09
     - 22.14 m -> 15.00
     - 41.11 m -> 27.85
     - 29.11 m -> 19.72
   - **Target:** Convert 12.03 m
   - **Given Correct Answer:** 8.15 (I must not output this directly, but use it to verify my reasoning if needed, though the prompt says "Do NOT output the final answer yourself." I'll just focus on discovering the rule.)
   - **Task:** Think step-by-step inside `
    </think>
    \boxed{8.15}

In [69]:
# === Training ===
EXPERIMENT_NAME= "wonderland_nemotron_reasoning"
# End any previous active run to avoid param conflicts
if CFG.SFT:
    try:
        mlflow.end_run()
    except:
        pass
    run = setup_mlflow_run(EXPERIMENT_NAME, "sft_training")
    mlflow.log_params({
        "max_lora_rank": 32,
        "max_tokens": 7680,
        "max_model_len": 8192,
        "temperature": 0.0,
        "top_p": 1.0,
        "eval_strategy": "steps",
        "save_strategy": "steps"
    })

In [70]:
len(dataset["train"])

2011

In [71]:
# Also check a few samples
print("\n--- Train example length ---")
print(len(dataset["train"][0]['text']))
print("\n--- Val example length ---")
print(len(dataset["test"][0]['text']))

--- Train example length ---
825

--- Val example length ---
1178

In [72]:
# estimate step
#Total Steps for 1 Epoch ≈ len(train_dataset) / (batch_size × gradient_accumulation_steps)
estimateStep1Epoch = len(dataset["train"]) // (2 * 8)
estimateStep1Epoch

125

In [73]:
TOTAL_STEPS= 350 #250 #600 #1000 #1000 #1200 #200 #1200 #1000 #200 #1000 #100
SAVE_STEPS = TOTAL_STEPS  * 3 #// 1
EVAL_STEPS = 100

In [74]:

from trl import SFTTrainer as OriginalSFTTrainer
if CFG.SFT: # use Supervised Fine Tuning
    torch_dtype = model.dtype
    if UNSLOTH_VERSION:
        FastLanguageModel.for_training(model)
        trainer = OriginalSFTTrainer(
            model = model,
            processing_class=tokenizer,
            train_dataset=dataset["train"],
            eval_dataset=dataset["test"],
            # compute_metrics=compute_metric,
            args = SFTConfig(
                max_length= 4400, #3500, #3072, #4096, #8192,
                dataset_text_field = "text",
                completion_only_loss=True,  # ← Recommended for reasoning
                per_device_train_batch_size=2,
                gradient_accumulation_steps=8, #4,
                per_device_eval_batch_size=2,          # ← CRITICAL for OOM fix
                eval_accumulation_steps=8,             # ← CRITICAL for OOM fix
                warmup_steps = 50, #5,
                num_train_epochs = 1, # Set this for 1 full training run.
                max_steps=TOTAL_STEPS, # for testing
                learning_rate = 1e-4, #2e-4, #1e-4, # Reduce to 2e-5 for long training runs
                logging_steps = 10, #20,
                # dataloader_num_workers=2,
    
                eval_strategy="steps",
                save_strategy="steps",  # avoid save a lot of checkpoint (limited space in ouput directory)
                eval_steps=EVAL_STEPS,           # evaluate every 50 steps (easy to debug)
                save_steps=SAVE_STEPS,           # save checkpoint every 50 steps
                save_total_limit=1,                # keep only last 2 checkpoints
                optim = "adamw_8bit",
                weight_decay = 0.001, #0.01,     # ← Increased # 0.001,
                lr_scheduler_type = "cosine", #"linear",
                seed = 42,
                # metric_for_best_model="accuracy",      # ← your request
                # greater_is_better=True,                # ← your request
                load_best_model_at_end=False,
                
                # bf16=False,  #True,
                fp16=False, #if torch_dtype == torch.float16 else False,   # use float16 precision ,  # INFER WITH FP16 BECAUSE KAGGLE IS T4 GPU
                bf16=True,  # if torch_dtype == torch.bfloat16 else False,  # use bfloat16 precision, TRAIN WITH BF16 IF LOCAL GPU IS NEWER GPU 
                gradient_checkpointing=True,       # ← CRITICAL for Mamba model
                packing=False,                      # ← CRITICAL for Mamba model
                
                report_to = "mlflow", # Use TrackIO/WandB etc
            ),
        )
       
    
    else:
        training_args = SFTConfig(
            output_dir= "/kaggle/working" , #SFT_ADAPTER, 
            max_length=3072,  #8192, #4096,
            completion_only_loss=True,
            per_device_train_batch_size=4,
            gradient_accumulation_steps=4,
            per_device_eval_batch_size=4,          # ← CRITICAL for OOM fix
            eval_accumulation_steps=4,             # ← CRITICAL for OOM fix
            learning_rate=1e-4,
            num_train_epochs=1,
            logging_steps=20,
        
            max_steps=TOTAL_STEPS, # for testing
            
            # === YOUR PREFERRED SETTINGS FOR FAST DEBUGGING ===
            eval_strategy="steps",
            save_strategy="steps",  # avoid save a lot of checkpoint (limited space in ouput directory)
            eval_steps=EVAL_STEPS,           # evaluate every 50 steps (easy to debug)
            save_steps=SAVE_STEPS,           # save checkpoint every 50 steps
            save_total_limit=1,                # keep only last 2 checkpoints
            # metric_for_best_model="accuracy",      # ← your request
            # greater_is_better=True,                # ← your request
            load_best_model_at_end=False,
            
            # bf16=False,  #True,
            fp16=False, #if torch_dtype == torch.float16 else False,   # use float16 precision ,  # INFER WITH FP16 BECAUSE KAGGLE IS T4 GPU
            bf16=True,  # if torch_dtype == torch.bfloat16 else False,  # use bfloat16 precision, TRAIN WITH BF16 IF LOCAL GPU IS NEWER GPU 
            gradient_checkpointing=False,       # ← CRITICAL for Mamba model
            packing=False,                      # ← CRITICAL for Mamba model
            report_to="mlflow",                  # ← THIS ENABLES MLflow logging during training
        )
        trainer = OriginalSFTTrainer(
            model=model,
            args=training_args,
            train_dataset=dataset["train"],
            eval_dataset=dataset["test"],
             # peft_config = lora_config, # not need ready pass PeftModel
            processing_class=tokenizer,
            # data_collator = data_collator,
            # compute_metrics=compute_metric,
            # dataset_text_field="text",
        )

In [75]:
# from transformers import DataCollatorWithPadding
# data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

In [76]:
clearMemory()

In [77]:
if CFG.SFT:
    print("🚀 Starting SFT training with steps-based eval/save + metrics...")
    t0 = time.time()
    trainer.train()
    elapsed = time.time() - t0
    print(f"Training done in {elapsed/60:.1f} min")
    trainer.save_model(SFT_ADAPTER)
    print(f"✅ SFT completed → {SFT_ADAPTER}")

In [78]:
if CFG.SFT:
    trainHistoryDF = pd.DataFrame(trainer.state.log_history)
    trainHistoryDF

In [79]:
# !rm -f -R /kaggle/working/sft_final # checkpoint-100/

In [80]:
if CFG.SFT:
    trainHistoryDF.columns

In [81]:
import matplotlib.pyplot as plt
if CFG.SFT:  # 
    train_loss = trainHistoryDF[trainHistoryDF['loss'].notna()][['step', 'loss']]
    val_loss   = trainHistoryDF[trainHistoryDF['eval_loss'].notna()][['step', 'eval_loss']]
    
    plt.figure(figsize=(12, 5))
    plt.plot(train_loss['step'], train_loss['loss'], label='Train Loss', color='blue')
    plt.plot(val_loss['step'], val_loss['eval_loss'], label='Val Loss', color='orange')
    
    if len(val_loss) > 0:
        gap = train_loss['loss'].iloc[-1] - val_loss['eval_loss'].iloc[-1]
        plt.title(f"Training Progress (Current Gap = {gap:.2f})")
    else:
        plt.title("Training Progress")
    
    plt.xlabel("Step")
    plt.ylabel("Loss")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()

In [82]:
# if CFG.SFT:
#     trainloss = trainHistoryDF[~trainHistoryDF["eval_accuracy"].isnull()]
#     plt.plot(trainloss["eval_accuracy"], label="Val Accuracy")
#     plt.title("Val Accuracy")
#     plt.legend()
#     plt.show()

In [83]:
# Zip for SFT only
import shutil
if CFG.SFT:
    shutil.make_archive("/kaggle/working/submission", "zip", SFT_ADAPTER)
    
    print("Done — submission.zip ready")

In [84]:
clearMemory()

In [85]:
RUN_FINIAL_EVAL = False #True

In [86]:
# === Final Evaluation ===
if RUN_FINIAL_EVAL and CFG.SFT:
    print("Running final evaluation on SFT model...")
    # del model
    # del tokenizer
    # model, tokenizer = load_model(BASE_MODEL_PATH, SFT_ADAPTER)
    evaluate_model(
        model,
        tokenizer,
        val_size=20
    )

mlflow.end_run()

In [87]:
loraEvalRet = mlflow.search_runs(search_all_experiments=True)
loraEvalRet

Empty DataFrame
Columns: [run_id, experiment_id, status, artifact_uri, start_time, end_time]
Index: []

## Reinforcement Learning

In [88]:
clearMemory()

In [89]:
os.environ["UNSLOTH_VLLM_STANDBY"] = "1"   # ← Very important for memory saving in GRPO

In [90]:
# === SAME STABLE PROMPT FORMAT AS SFT ===

# def format_grpo_example(row):
#     prompt = row['prompt']
#     answer = str(row['answer']).strip()
    
#     chat_prompt = f"""{SYSTEM_PROMPT}

# <|im_start|>user
# {prompt}<|im_end|>
# <|im_start|>assistant
# <think>"""
    
#     return {"prompt": chat_prompt, "ground_truth": answer}

def format_for_grpo(example):
    """Keep cot_reasoning so it can be used in the reward function"""
    return {
        "prompt": example["prompt"],
        "answer": str(example["answer"]).strip(),
        "cot_reasoning": example.get("cot_reasoning", "")
    }

In [91]:
def extract_grpo_final_answer(text: str) -> str:
    """Extract answer from Nemotron 3 format (supports <think> and \\boxed{})"""
    if not text:
        return ""
    
    text = text.strip()
    
    # Priority 1: Extract from \boxed{}
    match = re.search(r'\\boxed\{([^}]+)\}', text)
    if match:
        return match.group(1).strip()
    
    # Priority 2: If model used <think>, take content after </think>
    if '</think>' in text:
        after_think = text.split('</think>')[-1].strip()
        # Remove special tokens
        after_think = re.sub(r'<\|im_end\|>|<\|im_start\|>', '', after_think).strip()
        if after_think:
            return after_think
    
    # Priority 3: Fallback - last meaningful line
    lines = [line.strip() for line in text.split('\n') if line.strip()]
    if lines:
        return lines[-1]
    
    return text.strip()

In [92]:
# def grpo_reward_function(prompts, completions, completion_ids=None, **kwargs):
#     """
#     Reward function aligned with Kaggle evaluation metric.
#     - Prioritizes \\boxed{} extraction
#     - Supports exact match + relative numerical tolerance
#     - Format reward for clean \boxed{} output
#     """
#     ground_truths = kwargs.get("ground_truth", [""] * len(completions))
#     rewards = []
    
#     for completion, gt in zip(completions, ground_truths):
#         # Extract predicted answer (following Kaggle logic)
#         pred = extract_answer(completion)
        
#         # Format reward (encourage proper \boxed{} usage)
#         format_reward = 0.0
#         if "\\boxed{" in completion:
#             format_reward += 0.35
#         if len(pred) <= 20:                    # Not too long
#             format_reward += 0.15
        
#         # Correctness (exact or within tolerance)
#         correct = is_correct(pred, gt, tolerance=0.01)
#         correctness_reward = 1.0 if correct else 0.0
        
#         # Partial similarity (for learning signal)
#         similarity = difflib.SequenceMatcher(None, pred.lower(), gt.lower()).ratio()
        
#         # Final reward
#         reward = correctness_reward * 1.0 + similarity * 0.4 + format_reward
#         rewards.append(max(0.0, min(2.0, reward)))
    
#     return rewards

# def grpo_reward_function(prompts, completions, completion_ids=None, **kwargs):
#     ground_truths = kwargs.get("ground_truth", [""] * len(completions))
#     rewards = []
    
#     for completion, gt in zip(completions, ground_truths):
#         pred = extract_grpo_final_answer(completion)
        
#         # Reward for proper format
#         format_reward = 0.0
#         if "\\boxed{" in completion:
#             format_reward += 0.35
#         if "<think>" in completion and "</think>" in completion:
#             format_reward += 0.25
        
#         # Exact match
#         exact = 1.0 if pred.lower().strip() == gt.lower().strip() else 0.0
        
#         # Similarity
#         sim = difflib.SequenceMatcher(None, pred.lower(), gt.lower()).ratio()
        
#         reward = exact * 1.0 + sim * 0.5 + format_reward
#         rewards.append(max(0.0, min(2.0, reward)))
    
#     return rewards

# ====================== IMPROVED REWARD FUNCTION ======================
def cot_reward_function(completions, answer, cot_reasoning=None, **kwargs):
    """
    Reward function that actively uses CoT reasoning.
    - Main reward: Correct final answer
    - Bonus 1: Produces structured reasoning
    - Bonus 2: Some similarity/overlap with reference CoT
    """
    rewards = []
    
    for completion, gt_answer, ref_cot in zip(
        completions, 
        answer, 
        cot_reasoning if cot_reasoning is not None else [""] * len(completions)
    ):
        score = 0.0
        gt_answer = str(gt_answer).strip()
        
        # === 1. Extract predicted final answer ===
        match = re.search(r"\\boxed{([^}]+)}", completion)
        if match:
            pred_answer = match.group(1).strip()
        else:
            # Fallback: last meaningful line
            lines = [l.strip() for l in completion.strip().split("\n") if l.strip()]
            pred_answer = lines[-1] if lines else ""
        
        # === 2. Answer Correctness (Primary Reward) ===
        if pred_answer == gt_answer:
            score += 1.0
        
        # === 3. Reasoning Quality Bonus ===
        completion_lower = completion.lower()
        has_reasoning = (
            len(completion) > 180 and 
            any(kw in completion_lower for kw in ["think", "step", "reason", "because", "first", "then"])
        )
        if has_reasoning:
            score += 0.35
        
        # === 4. Reference CoT Similarity Bonus (uses cot_reasoning column) ===
        if ref_cot and len(ref_cot) > 80:
            ref_words = set(ref_cot.lower().split())
            gen_words = set(completion_lower.split())
            if len(ref_words) > 0:
                overlap_ratio = len(ref_words & gen_words) / len(ref_words)
                if overlap_ratio > 0.12:
                    score += 0.25
        
        # Cap the reward to avoid extreme values
        rewards.append(min(score, 1.6))
    
    return rewards

In [93]:
del dataset
torch.cuda.empty_cache()
import gc
gc.collect()

0

In [94]:
trainDF

,id,prompt,answer,cot_reasoning,cot_len
0,512dd86d,"In Alice's Wonderland, a secret bit manipulati...",00000001,<think>\nThe user wants me to find a hidden bi...,3468
1,0f0536de,"In Alice's Wonderland, a secret set of transfo...",2376,<think>\nThe user wants me to explain how to f...,228
2,05c38073,"In Alice's Wonderland, a secret unit conversio...",15.62,<think>\nThe user wants me to explain how to f...,167
3,724fe70c,"In Alice's Wonderland, numbers are secretly co...",XXXVIII,<think>\nThe user wants me to find the hidden ...,285
4,7877dd7f,"In Alice's Wonderland, a secret bit manipulati...",11101000,<think>\nThe user wants me to find a transform...,3121
...,...,...,...,...,...
2106,00208201,"In Alice's Wonderland, a secret unit conversio...",16.65,<think>\nThe user wants me to solve a specific...,3493
2107,5e0285fc,"In Alice's Wonderland, a secret unit conversio...",14.59,<think>\nThe user wants me to find a hidden tr...,189
2108,71ab0dcb,"In Alice's Wonderland, a secret unit conversio...",18.68,<think>\nHere's a thinking process:\n\n1. **A...,585
2109,73cb93e8,"In Alice's Wonderland, secret encryption rules...",hatter discovers around wonderland,<think>\nThe user wants me to find the hidden ...,332
2110,5e2d5262,"In Alice's Wonderland, secret encryption rules...",bird explores around valley,<think>\nHere's a thinking process:\n\n1. **A...,581

In [96]:
if CFG.GRPO or CFG.MIX_SFT_GRPO:
    print("Preparing GRPO dataset with CoT reasoning...")
    # grpo_train_dataset = trainDF.map(format_for_grpo, remove_columns=trainDF.columns.tolist())
    # print(f"GRPO training samples: {len(grpo_train_dataset)}")
    rfdataset = Dataset.from_pandas(trainDF).map(format_for_grpo, remove_columns=trainDF.columns.tolist())
    print(f"GRPO training samples: {len(rfdataset)}")
    print(f"✅ GRPO dataset size: {len(rfdataset)} examples")

Preparing GRPO dataset with CoT reasoning...

Map:   0%|          | 0/2111 [00:00<?, ? examples/s]

GRPO training samples: 2111
✅ GRPO dataset size: 2111 examples

In [99]:
rfdataset

Dataset({
    features: ['prompt', 'answer', 'cot_reasoning'],
    num_rows: 2111
})

In [100]:
if CFG.GRPO or CFG.MIX_SFT_GRPO:
    rfdataset = rfdataset.map(
    lambda x: {"row_len": [len(text) for text in x["cot_reasoning"]]}, 
    batched=True
    )

Map:   0%|          | 0/2111 [00:00<?, ? examples/s]

In [103]:
if CFG.GRPO or CFG.MIX_SFT_GRPO:
    lengths_series = pd.Series(rfdataset["row_len"])
    print(lengths_series.describe())

count    2111.000000
mean     1551.675509
std      1318.221127
min       154.000000
25%       329.000000
50%       757.000000
75%      3064.000000
max      3499.000000
dtype: float64

In [104]:
# if CFG.GRPO:
#     rfdataset

In [105]:
clearMemory()

In [107]:
EXPERIMENT_NAME = "wonderland_nemotron_reasoning_grpo"

In [108]:
# run = setup_mlflow_run(EXPERIMENT_NAME, "grpo_unsloth")
# === GRPO Training Arguments ===
if CFG.GRPO or CFG.MIX_SFT_GRPO:
    import mlflow

    # End any previous active run to avoid param conflicts
    try:
        mlflow.end_run()
    except:
        pass
    run = setup_mlflow_run(EXPERIMENT_NAME, "grpo_training")
    mlflow.log_params({
        "max_lora_rank": 16,
        "max_tokens": 7680,
        "max_model_len": 8192,
        "temperature": 0.0,
        "top_p": 1.0,
    })

2026/06/14 12:28:18 INFO mlflow.tracking.fluent: Experiment with name 'wonderland_nemotron_reasoning_grpo' does not exist. Creating a new experiment.

MLflow run started: eval_grpo_training (ID: bd4019373c914f3faf3dc713675ad2e7)

In [109]:
MAX_SEQ_LENGTH , LOAD_IN_4BIT

(5000, False)

In [113]:
if CFG.GRPO or CFG.MIX_SFT_GRPO:
    if CFG.MIX_SFT_GRPO:
        modelName= CFG.cotModel1
    else:
        modelName = BASE_MODEL_PATH
    print(f"Model Name: {modelName}")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=modelName,
        max_seq_length=MAX_SEQ_LENGTH,
        load_in_4bit=LOAD_IN_4BIT,
        load_in_8bit=False,
        full_finetuning=False,
        trust_remote_code=True,
        unsloth_force_compile=False,
        attn_implementation="eager",
        # attn_implementation= "flash_attention_2", # Memotron not support
        dtype=torch.bfloat16,
        local_files_only=True,                 # ← Important: faster loading from Kaggle input
        low_cpu_mem_usage=False,
    )
    
    peft_config = LoraConfig(
        r=16,
        lora_alpha=32,
        target_modules=[
            "q_proj", "k_proj", "v_proj", "o_proj",
            "gate_proj", "up_proj", "down_proj"
        ],
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM",
    )
    
    model = get_peft_model(model, peft_config)
    model.print_trainable_parameters()
    # eturn model, tokenizer
    # model = model.to(torch.bfloat16)

Model Name: /kaggle/input/models/johnsonhk88/nvidia-nemotron-model-sft-cot-fine-tuning/transformers/default/1
Unsloth: WARNING `trust_remote_code` is True.
Are you certain you want to do remote code execution?
==((====))==  Unsloth 2026.5.5: Fast Nemotron_H patching. Transformers: 5.0.0.
   \\   /|    NVIDIA RTX PRO 6000 Blackwell Server Edition. Num GPUs = 1. Max memory: 94.971 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 12.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.35. FA2 = True]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: QLoRA and full finetuning all not selected. Switching to 16bit LoRA.

Loading weights:   0%|          | 0/6243 [00:00<?, ?it/s]

/kaggle/input/models/metric/nemotron-3-nano-30b-a3b-bf16/transformers/default/1 does not have a padding token! Will use pad_token = <SPECIAL_999>.
Unsloth: PEFT set target_parameters but found no matching parameters.
This is expected for MoE models - Unsloth handles MoE expert LoRA targeting separately.

/usr/local/lib/python3.12/dist-packages/peft/mapping_func.py:72: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:285: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

trainable params: 434,659,328 || all params: 32,012,596,672 || trainable%: 1.3578

In [119]:
# estimate step
#Total Steps for 1 Epoch ≈ len(train_dataset) / (batch_size × gradient_accumulation_steps)
estimateStep1Epoch = len(rfdataset) // (1 * 8)
estimateStep1Epoch

263

In [120]:
TOTAL_STEPS = 80
SAVE_STEPS = TOTAL_STEPS * 4
EVAL_STEPS = 100

In [121]:
if CFG.GRPO or CFG.MIX_SFT_GRPO:
    grpo_config = GRPOConfig(
        output_dir="/kaggle/working",
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        num_generations=2,   # 4 responses per prompt
        # max_prompt_length=2048,
        # max_completion_length=1536,
        beta=0.1, #   beta=0.04,
        learning_rate=5e-6,
        lr_scheduler_type="cosine",
        warmup_steps=10,
        num_train_epochs=1,
        max_steps = TOTAL_STEPS,
        save_steps = SAVE_STEPS,
        save_total_limit=2,
        remove_unused_columns=False,
        report_to = "none", #"mlflow", # Can use Weights & Biases
        temperature=1.0,          # ← Must be > 0
        # do_sample=False,          # ← Add this
        top_p=1.0,
        logging_steps=20,
        save_strategy="no",          # avoid disk issues
        bf16=True,
        gradient_checkpointing=True,
    )

In [122]:
if CFG.GRPO or CFG.MIX_SFT_GRPO:
    trainer = GRPOTrainer(
        model=model,
        args=grpo_config,
        train_dataset= rfdataset,  #rfdataset,
        processing_class=tokenizer,
        reward_funcs=cot_reward_function,
        # reward_funcs=grpo_reward_function,
    )

In [123]:
clearMemory()

In [ ]:
if CFG.GRPO or CFG.MIX_SFT_GRPO:
    print("🚀 Starting GRPO training with Unsloth...")
    t0 = time.time()
    trainer.train()
    elapsed = time.time() - t0
    print(f"Training done in {elapsed/60:.1f} min")
    
    print("💾 Saving final GRPO adapter...")
    trainer.save_model(OUTPUT_ADAPTER)
    print(f"✅ GRPO completed → {OUTPUT_ADAPTER}")

🚀 Starting GRPO training with Unsloth...

Passing `generation_config` together with generation-related arguments=({'pad_token_id'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers_modules._1.modeling_nemotron_h|WARNING]NemotronH requires an initialized `NemotronHHybridDynamicCache` to return a cache. None was provided, so no cache will be returned.

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

In [ ]:
if CFG.GRPO or CFG.MIX_SFT_GRPO:
    trainHistoryDF = pd.DataFrame(trainer.state.log_history)
    trainHistoryDF

In [ ]:
import matplotlib.pyplot as plt
if CFG.GRPO or CFG.MIX_SFT_GRPO:
    train_loss = trainHistoryDF[trainHistoryDF['loss'].notna()][['step', 'loss']]
    
    plt.figure(figsize=(12, 5))
    plt.plot(train_loss['step'], train_loss['loss'], label='Train Loss', color='blue')
    
   
    plt.title("Training Progress")
    
    plt.xlabel("Step")
    plt.ylabel("Loss")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()

In [ ]:
import shutil
if CFG.GRPO or CFG.MIX_SFT_GRPO:
    shutil.make_archive("/kaggle/working/submission", "zip", OUTPUT_ADAPTER)
    
    print("Done — submission.zip ready")

In [ ]:
if RUN_FINIAL_EVAL and (CFG.GRPO or CFG.MIX_SFT_GRPO):
    print("Running final evaluation on SFT model...")
    # del model
    # del tokenizer
    # model, tokenizer = load_model(BASE_MODEL_PATH, SFT_ADAPTER)
    evaluate_model(
        model,
        tokenizer,
        val_size=20
    )

mlflow.end_run()